return {
    design_width = 240.0,
    design_height = 160.0,
    text_baseline_y_offset = 2.0,
    text_scale_multiplier = 1.5,
    draw_gauge_background = true,

    win_page_name_x = 0.0,
    win_page_name_y = 0.0,
    win_controls_x = 152.0,
    win_controls_y = 0.0,
    win_level_nick_x = 0.0,
    win_level_nick_y = 17.0,
    win_info_right_x = 120.0,
    win_info_right_y = 17.0,
    win_info_memo_x = 8.0,
    win_info_memo_y = 113.0,
    win_skills_right_x = 160.0,
    win_skills_right_y = 17.0,
    win_skills_exp_x = 48.0,
    win_skills_exp_y = 97.0,
    win_skills_ability_x = 8.0,
    win_skills_ability_y = 129.0,
    win_moves_right_x = 160.0,
    win_moves_right_y = 17.0,
    win_moves_type_x = 120.0,
    win_moves_type_y = 17.0,

    header_title_x = 4.0,
    header_title_y = 1.0,
    header_controls_align_width = 87.0,
    header_controls_y = 0.0,

    level_text_x = 4.0,
    species_text_x = 40.0,
    gender_symbol_x = 105.0,
    level_species_y = 2.0,
    mon_ball_icon_x = 98.0,
    mon_ball_icon_y = 80.0,
    mon_ball_icon_w = 16.0,
    mon_ball_icon_h = 16.0,
    shiny_star_x = 102.0,
    shiny_star_y = 36.0,
    shiny_star_w = 8.0,
    shiny_star_h = 8.0,

    eevee_sprite_x = 28.0,
    eevee_sprite_y = 33.0,
    eevee_sprite_w = 64.0,
    eevee_sprite_h = 64.0,

    info_dex_x = 47.0,
    info_dex_y = 5.0,
    info_name_x = 47.0,
    info_name_y = 19.0,
    info_type_icon_x = 167.0,
    info_type_icon_y = 51.0,
    info_type_icon_w = 32.0,
    info_type_icon_h = 12.0,
    info_ot_x = 47.0,
    info_ot_y = 49.0,
    info_id_x = 47.0,
    info_id_y = 64.0,
    info_item_x = 47.0,
    info_item_y = 79.0,
    info_memo_line1_x = 0.0,
    info_memo_line1_y = 3.0,
    info_memo_line2_x = 0.0,
    info_memo_line2_y = 16.0,

    skills_hp_text_x = 14.0,
    skills_hp_text_align_width = 63.0,
    skills_hp_text_y = 4.0,
    skills_hp_gauge_x = 166.0,
    skills_hp_gauge_y = 32.0,
    skills_hp_gauge_segments = 6,

    skills_stat_value_x = 50.0,
    skills_stat_align_width = 27.0,
    skills_attack_y = 22.0,
    skills_defense_y = 35.0,
    skills_spatk_y = 48.0,
    skills_spdef_y = 61.0,
    skills_speed_y = 74.0,

    skills_exp_value_x = 15.0,
    skills_exp_align_width = 63.0,
    skills_exp_points_y = 87.0,
    skills_next_level_y = 100.0,
    skills_exp_label_x = 26.0,
    skills_exp_label_y = 7.0,
    skills_next_label_x = 26.0,
    skills_next_label_y = 20.0,
    skills_ability_name_x = 66.0,
    skills_ability_name_y = 1.0,
    skills_ability_desc_x = 2.0,
    skills_ability_desc_y = 15.0,
    skills_exp_gauge_x = 150.0,
    skills_exp_gauge_y = 128.0,
    skills_exp_gauge_segments = 8,

    moves_name_x = 3.0,
    moves_name_base_y = 5.0,
    moves_row_step_y = 28.0,
    moves_pp_y_offset = 11.0,
    moves_pp_label_x = 36.0,
    moves_current_pp_x = 46.0,
    moves_current_pp_align_width = 16.0,
    moves_slash_x = 58.0,
    moves_max_pp_x = 64.0,
    moves_max_pp_align_width = 16.0,
    moves_type_icon_x_offset = 3.0,
    moves_type_icon_w = 32.0,
    moves_type_icon_h = 12.0,
}
